import { z } from "zod"

export const settingsSchema = z.object({
  deviceType: z.enum(["x4", "x3"]),
  orientation: z.number(),
  fontSize: z.number().min(14).max(48),
  fontWeight: z.number().min(100).max(900),
  lineHeight: z.number().min(80).max(200),
  margin: z.number().min(0).max(50),
  fontFace: z.string(),
  textAlign: z.number().min(-1).max(3),
  wordSpacing: z.number(),
  hyphenation: z.number().min(0).max(2),
  hyphenationLang: z.string(),
  ignoreDocMargins: z.boolean(),
  qualityMode: z.enum(["fast", "hq"]),
  enableDithering: z.boolean(),
  ditherStrength: z.number().min(0).max(100),
  enableNegative: z.boolean(),
  enableProgressBar: z.boolean(),
  progressPosition: z.enum(["top", "bottom"]),
  showProgressLine: z.boolean(),
  showChapterMarks: z.boolean(),
  showChapterProgress: z.boolean(),
  progressFullWidth: z.boolean(),
  showPageInfo: z.boolean(),
  showBookPercent: z.boolean(),
  showChapterPage: z.boolean(),
  showChapterPercent: z.boolean(),
  progressFontSize: z.number().min(10).max(20),
  progressEdgeMargin: z.number().min(0).max(30),
  progressSideMargin: z.number().min(0).max(30),
  fontHinting: z.number(),
  fontAntialiasing: z.number(),
  // Device
  deviceHost: z.string().default(""),
  devicePort: z.number().min(1).max(65535).default(81),
  deviceUploadPath: z.string().default("/"),
  deviceTransferMode: z.enum(["direct", "relay"]).default("direct"),
  rememberedDevices: z.string().default("[]"),
})

export type Settings = z.infer<typeof settingsSchema>

export const DEFAULT_SETTINGS: Settings = {
  deviceType: "x4",
  orientation: 0,
  fontSize: 22,
  fontWeight: 400,
  lineHeight: 120,
  margin: 20,
  fontFace: "Literata",
  textAlign: -1,
  wordSpacing: 100,
  hyphenation: 2,
  hyphenationLang: "auto",
  ignoreDocMargins: false,
  qualityMode: "fast",
  enableDithering: true,
  ditherStrength: 70,
  enableNegative: false,
  enableProgressBar: true,
  progressPosition: "bottom",
  showProgressLine: true,
  showChapterMarks: true,
  showChapterProgress: false,
  progressFullWidth: false,
  showPageInfo: true,
  showBookPercent: true,
  showChapterPage: true,
  showChapterPercent: false,
  progressFontSize: 14,
  progressEdgeMargin: 0,
  progressSideMargin: 0,
  fontHinting: 1,
  fontAntialiasing: 2,
  deviceHost: "",
  devicePort: 81,
  deviceUploadPath: "/",
  deviceTransferMode: "direct" as const,
  rememberedDevices: "[]",
}
